catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cat_index, name='cat-index'),
    path('cats/<int:cat_id>/', views.cat_detail, name='cat_detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cat-create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cat-update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cat-delete'),
    path('cats/<int:cat_id>/add-feeding/', views.add_feeding, name='add-feeding'),
    path('accounts/signup/', views.signup, name='signup')
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("cat_detail", kwargs={ "cat_id": self.id })
    

class Feeding(models.Model):
    date=models.DateField('Feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date'] 

main_app/forms.py
from django import forms
from .models import Feeding

class FeedingForm(forms.ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Cat
from .forms import FeedingForm

# Create your views here.
class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

@login_required
def cat_index(request):
    cats = Cat.objects.filter(user=request.user)
    return render(request, 'cats/index.html', { 'cats': cats})

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = ['name', 'breed', 'description', 'age']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    success_url = '/cats/'

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = ['breed', 'description', 'age']

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = '/cats/'

@login_required
def cat_detail(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    feeding_form = FeedingForm()
    return render(request, 'cats/detail.html', {
        'cat': cat, 'feeding_form': feeding_form
    })

@login_required
def add_feeding(request, cat_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.cat_id = cat_id
        new_feeding.save()
    return redirect('cat_detail', cat_id=cat_id)

def signup (request):
    error_message=''
    form = UserCreationForm(request.POST)
    if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('cat-index')
    else:
        error_message = 'Invalid sign up - Try again!'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Cat Collector</h1>
<hr />
<p class="page-content">
  I like long romantic walks down the produce aisle. Also, I am currently job
  seeking!
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/splash.svg' %}" />
    <title>ᓚᘏᗢ</title>
    <link rel="stylesheet" href="{% static './css/base.css' %}" />
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a class="home-link" href="/">
          <img src="{% static 'images/header-logo.svg' %}" alt="The Cat Collector Logo" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'cat-index' %}">All Cats</a></li>
            {% comment %} <li><a href="{% url 'toy-index' %}">All Toys</a></li> {% endcomment %}
            <li><a href="{% url 'cat-create' %}">Add a Cat</a></li>
            {% comment %} <li><a href="{% url 'toy-create' %}">Add a Toy</a></li> {% endcomment %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/cats/cat-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="cat-container">
  <div class="cat-img">
    <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
  </div>
  <div class="cat-details">
    <h1>{{ cat.name }}</h1>
    {% if cat.age > 0 %}
      <h2>A {{ cat.age }} year old {{ cat.breed }}</h2>
    {% else %}
      <h2>A {{ cat.breed }} kitten.</h2>
    {% endif %}
    <p>{{ cat.description }}</p>

    <div class="cat-actions">
        <a href="{% url 'cat-update' cat.id %}">Edit</a>
        <a href="{% url 'cat-delete' cat.id %}">Delete</a>
  </div>
</section>

<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Feedings</h2>
      <img
        src="{% static 'images/cat-cone.svg' %}"
        alt="An ice cream cone cat"
      />
      <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
      <img
        src="{% static 'images/kitty-kabob.svg' %}"
        alt="A kabob of kittens"
      />
    </div>
    <h3>Add a Feeding</h3>
<!-- Add just above the feedings table -->
    <h3>Add a Feeding</h3>
    <form
      action="{% url 'add-feeding' cat.id %}"
      method="post"
      class="subsection-content"
      autocomplete="off"
    >
      {% csrf_token %} 
      {{ feeding_form.as_p }}
      <button type="submit" class="btn submit">Add Feeding</button>
    </form>
    <h3>Past Feedings</h3>
      {% if cat.feeding_set.all.count %}
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Meal</th>
            </tr>
          </thead>
          <tbody>
            {% for feeding in cat.feeding_set.all %}
            <tr>
              <td>{{feeding.date}}</td>
              <td>{{feeding.get_meal_display}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <div class="subsection-content">
          <p>⚠️ {{cat.name}} is so hungry!</p>
        </div>
      {% endif %}
    </table>
  </section>
</div>

{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static './css/cats/cat-index.css' %}"/>
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>Cat List</h1>
  <img src="{% static 'images/cool-cat.svg' %}" alt="A cool cat" />
  <img src="{% static 'images/happy-cat.svg' %}" alt="A happy cat" />
  <img src="{% static 'images/teacup-cat.svg' %}" alt="A cat in a teacup" />
  <img src="{% static 'images/cat-in-box.svg' %}" alt="A cat in a box" />
</section>

<section class="card-container">
  {% for cat in cats %}
    <div class="card">
      <a href="{% url 'cat_detail' cat.id %}">
        <div class="card-content">
          <div class="card-img-container">
            <img
              src="{% static 'images/sk8r-boi-cat.svg' %}"
              alt="A skater boy cat"
            />
          </div>
          <h2 class="card-title">{{ cat.name }}</h2>
          {% if cat.age > 0 %}
          <p>A {{ cat.age }} year old {{ cat.breed }}</p>
          {% else %}
          <p>A {{ cat.breed }} kitten.</p>
          {% endif %}
          <p><small>{{ cat.description }}</small></p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}

<section class="logo-container">
  <div class="cat-container">
    <img src="{% static 'images/splash.svg' %}" alt="The Cat Collector Cat" />
  </div>
  <img src="{% static 'images/logotype.svg' %}" alt="Text reads: Cat Collector" />
</section>

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Cat?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<h2>Are you sure you want to delete {{ cat.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'cat_detail' cat.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}

<div class="page-header">
    {% if cat %}
      <h1>Edit {{ cat.name }}</h1>
    {% else %}
      <h1>Add a Cat</h1>
    {% endif %}
  </div>

<form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}